
# █░█ █▀ █▀▀ █▀█   █▀█ █▀█ █▀▀ █▀▀ █▀
# █▄█ ▄█ ██▄ █▀▄   █▀▀ █▀▄ ██▄ █▀░ ▄█

# Set your personal hyprland configuration here
# For a sample file, please refer to https://github.com/prasanthrangan/hyprdots/blob/main/Configs/.config/hypr/userprefs.t2

# exec-once = hyprshade auto
exec-once = discord --start-minimized

# █ █▄░█ █▀█ █░█ ▀█▀
# █ █░▀█ █▀▀ █▄█ ░█░

input {
  touchpad {
    natural_scroll = yes
    disable_while_typing = true
  }
}

# █▀▄▀█ █▀█ █▄░█ █ ▀█▀ █▀█ █▀█ █▀
# █░▀░█ █▄█ █░▀█ █ ░█░ █▄█ █▀▄ ▄█

# monitor = eDP-1, 2560x1600@60, auto, auto
monitor = eDP-1, 2560x1600@240, auto, auto

# █░█░█ █ █▄░█ █▀▄ █▀█ █░█░█   █▀█ █░█ █░░ █▀▀ █▀
# ▀▄▀▄▀ █ █░▀█ █▄▀ █▄█ ▀▄▀▄▀   █▀▄ █▄█ █▄▄ ██▄ ▄█

# Android Emulator
windowrule = float true, match:class ^(Emulator)$ # Signal-Gtk
windowrule {
	name = Android-Emulator
	float = true
	move= 1303 39
	size= 256 576

	match:class = Emulator
	match:title = "Android Emulator - flutter_emulator:5554"
}

# zen browser
# windowrulev2 = opacity 1, class:^(zen)$
# windowrulev2 = noborder, class:^(zen)$

# zen Picture In Picture
windowrule {
		name = Zen-PiP
    opacity = 1
    float = true
    pin = true
    move = 1016 666
    size = 583 333

		match:class = zen
		match:title = Picture-in-Picture
}

# MPV
windowrule {
		name = Mpv-PiP
    opacity = 1
    float = true
    pin = true
    move = 1016 666
    size = 583 333

		match:class = mpv
}

# Kitty
# windowrulev2 = noborder, class:^(kitty)$
# windowrulev2 = opacity 1,class:^(kitty)$

# Neovide
# windowrulev2 = opacity 1, class:^(neovide)$
# windowrulev2 = noborder, class:^(neovide)$
# windowrulev2 = center, class:^(neovide)$

# Neovim
# windowrulev2 = rounding 5, class:^(kitty)$, title:^(.*NVIM.*)$

# Ghostty
# windowrulev2 = noborder, class:^(com.mitchellh.ghostty)$

# █▄▀ █▀▀ █▄█ █▄▄ █ █▄░█ █▀▄ █ █▄░█ █▀▀ █▀
# █░█ ██▄ ░█░ █▄█ █ █░▀█ █▄▀ █ █░▀█ █▄█ ▄█

# Switch workspaces to a relative workspace
bind = $mainMod+Ctrl, j, workspace, r+1
bind = $mainMod+Ctrl, k, workspace, r-1

# Move/Change window focus
bind = $mainMod, h, movefocus, l
bind = $mainMod, l, movefocus, r
bind = $mainMod, k, movefocus, u
bind = $mainMod, j, movefocus, d

animation = workspaces, 0, 8, default, slidefadevert
animation = fade, 0

# bind = $mainMod, m, exec, zen-browser # toggle pin on focused window

bind = Alt, l, movewindow, r
bind = Alt, h, movewindow, l
bind = Alt, j, movewindow, d
bind = Alt, k, movewindow, u

bind = $mainMod, o, exec, zen-browser http://localhost:4096

bind = $mainMod, D, exec, ~/.config/hypr/scripts/start-dev-workspace.sh
