[window]
opacity = 0.8
blur = true

[window.padding]
x = 15
y = 15

[font.normal]
family = "JetBrainsMonoNerdFont"
style = "Regular"

[font.bold]
family = "JetBrainsMonoNerdFont"
style = "Bold"

[font.italic]
family = "JetBrainsMonoNerdFont"
style = "Italic"
