# ~/.config/starship.toml

[username]
style_user = '190 bold'
style_root = 'black bold'
format = '[$user]($style)'
disabled = false
show_always = true
aliases = { "corpuser034g" = "matchai" }

[hostname]
ssh_only = false
format = '[$ssh_symbol](bold blue) on [$hostname](bold red) '
trim_at = '.companyname.com'
disabled = false

[cmd_duration]
min_time = 500
format = 'underwent [$duration](bold yellow)'

[kubernetes]
format = 'on [⛵ ($user on )($cluster in )$context \($namespace\)](dimmed green) '
disabled = false
contexts = [
  { context_pattern = "dev.local.cluster.k8s", style = "green", symbol = "💔 " },
]
